repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: check-yaml
  - id: check-case-conflict
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
- repo: https://github.com/glotzerlab/fix-license-header
  rev: 43eb3ff2d02cba5e572f86af5c15337823fb2c66
  hooks:
  - id: fix-license-header
    name: Fix license headers (Python)
    types_or: [python]
    args:
    - --license-file=LICENSE
    - --add=Part of the Glotzerlab jetstream2 administration scripts, released under the
    - --add=BSD 3-Clause License.
    - --keep-before=#!
- repo: https://github.com/google/yapf
  rev: 'v0.32.0'
  hooks:
  - id: yapf
- repo: https://github.com/PyCQA/flake8
  rev: '6.0.0'
  hooks:
  - id: flake8
    additional_dependencies:
    - pep8-naming==0.13.2
    - pydocstyle==6.1.1
    - flake8-docstrings==1.6.0
    - flake8-rst-docstrings==0.3.0
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout
