repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.1.0'
  hooks:
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: check-yaml
  - id: check-case-conflict
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
- repo: https://github.com/google/yapf
  rev: 'v0.32.0'
  hooks:
  - id: yapf
- repo: https://github.com/PyCQA/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    additional_dependencies:
    - pep8-naming==0.12.1
    - pydocstyle==6.1.1
    - flake8-docstrings==1.6.0
    - flake8-rst-docstrings==0.2.3
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout
