- name: Update action runners.
  hosts: action_runners

  tasks:
    - name: Fetch activity logs
      ansible.builtin.fetch:
        src: active-2023.log
        dest: activity-logs/{{ inventory_hostname }}
        flat: yes
