all:
  children:
    action_runners:
      vars:
        ansible_user: exouser

      children:
#        gpu:
#          vars:
#            labels: gpu-test
#          hosts:
#            actions-runner-1:
#              ansible_host: 149.165.159.180

        cpu:
          vars:
            labels: CPU
          hosts:
            actions-runner-cpu-0:
              ansible_host: 149.165.159.48
            actions-runner-cpu-1:
              ansible_host: 149.165.159.174
            actions-runner-cpu-2:
              ansible_host: 149.165.159.243
            actions-runner-cpu-3:
              ansible_host: 149.165.159.227
            actions-runner-cpu-4:
              ansible_host: 149.165.159.34
            actions-runner-cpu-6:
              ansible_host: 149.165.159.58
            actions-runner-cpu-8:
              ansible_host: 149.165.159.161
            actions-runner-cpu-9:
              ansible_host: 149.165.159.120
