all:
  children:
    action_runner_managers:
      vars:
        ansible_user: exouser

      hosts:
        actions-runner-manager:
          ansible_host: 149.165.175.133

    action_runners:
      vars:
        ansible_user: exouser

      children:
        gpu:
          vars:
            labels: GPU
          hosts:
            actions-runner-gpu-0:
              ansible_host: 149.165.168.66
            actions-runner-gpu-1:
              ansible_host: 149.165.174.153
            actions-runner-gpu-2:
              ansible_host: 149.165.170.93
            actions-runner-gpu-3:
              ansible_host: 149.165.172.12

        cpu:
          vars:
            labels: CPU
          hosts:
            actions-runner-cpu-1:
              ansible_host: actions-runner-cpu-1-of-8.dmr140129.projects.jetstream-cloud.org
            actions-runner-cpu-2:
              ansible_host: actions-runner-cpu-2-of-8.dmr140129.projects.jetstream-cloud.org
            actions-runner-cpu-3:
              ansible_host: actions-runner-cpu-3-of-8.dmr140129.projects.jetstream-cloud.org
            actions-runner-cpu-4:
              ansible_host: actions-runner-cpu-4-of-8.dmr140129.projects.jetstream-cloud.org
            actions-runner-cpu-5:
              ansible_host: actions-runner-cpu-5-of-8.dmr140129.projects.jetstream-cloud.org
            actions-runner-cpu-6:
              ansible_host: actions-runner-cpu-6-of-8.dmr140129.projects.jetstream-cloud.org
            actions-runner-cpu-7:
              ansible_host: actions-runner-cpu-7-of-8.dmr140129.projects.jetstream-cloud.org
            actions-runner-cpu-8:
              ansible_host: actions-runner-cpu-8-of-8.dmr140129.projects.jetstream-cloud.org
