all:
  children:
    actions_runners:
      vars:
        ansible_user: exouser

      children:
        gpu:
          vars:
            labels: gpu-test
          hosts:
            actions-runner-1:
              ansible_host: 149.165.159.180

        cpu:
          vars:
            labels: CPU
          hosts:
            actions-runner-cpu-0:
              ansible_host: 149.165.159.48
