name: Start action runners

on:
  # Start the runners every weekday.
  schedule:
      - cron:  '0 13 * * 1-5'

  pull_request:

  workflow_dispatch:

jobs:
  start:
    name: Test start composite action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
      - name: Start action runners
        uses: ./start
        with:
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
          number: 1
