name: Start

on:
  workflow_call:
    inputs:
      number:
        description: 'Number of runners to start.'
        required: false
        default: -1
        type: number

    secrets:
      OS_APPLICATION_CREDENTIAL_ID:
        required: true
      OS_APPLICATION_CREDENTIAL_SECRET:
        required: true

    outputs:
      active:
        description: "The number of active runners."
        value: ${{ jobs.action_runners.outputs.active }}

jobs:
  action_runners:
    name: action runners
    runs-on: ubuntu-latest
    outputs:
      active: ${{ steps.start.outputs.active }}
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        repository: glotzerlab/jetstream2-admin
        ref: reusable-workflow
    # Python 3.9 is the latest possible because netifaces has no new releases
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.9"
    - name: Install openstack
      uses: glotzerlab/workflows/setup-uv@5cfac9da9cb78e16ae97a9119b6fd13c1c2d6f5e # 0.1.0
      with:
        lockfile: ".github/workflows/requirements.txt"
    - id: start
      name: Start action runners
      run: |
        echo "active=$(python3 start/start-action-runners.py ${{ inputs.number }})" >> $GITHUB_OUTPUT
      env:
        OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        OS_AUTH_TYPE: v3applicationcredential
        OS_AUTH_URL: https://js2.jetstream-cloud.org:5000/v3/
        OS_IDENTITY_API_VERSION: 3
        OS_REGION_NAME: "IU"
        OS_INTERFACE: public
