name: Start

on:
  workflow_call:
    inputs:
      number:
        description: 'Number of runners to start.'
        required: false
        default: -1
        type: number
      ref:
        description: "Repository ref to clone (for testing)."
        required: false
        default: v1.5.1
        type: string

    secrets:
      OS_APPLICATION_CREDENTIAL_ID:
        required: false
      OS_APPLICATION_CREDENTIAL_SECRET:
        required: false

    outputs:
      active:
        description: "The number of active runners."
        value: ${{ jobs.action_runners.outputs.active }}

jobs:
  action_runners:
    name: action runners
    runs-on: ubuntu-latest
    outputs:
      active: ${{ steps.start.outputs.active }}
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: glotzerlab/jetstream2-admin
        ref: ${{ inputs.ref }}
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.14"
    - name: Install openstack
      uses: glotzerlab/workflows/setup-uv@00c67cb577c36bdc2570845fc62d1a30e3383012 # 0.14.0
      with:
        lockfile: ".github/workflows/requirements.txt"
    - id: start
      name: Start action runners
      run: |
        echo "active=$(python3 start/start-action-runners.py ${{ inputs.number }})" >> $GITHUB_OUTPUT
      env:
        OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        OS_AUTH_TYPE: v3applicationcredential
        OS_AUTH_URL: https://js2.jetstream-cloud.org:5000/v3/
        OS_IDENTITY_API_VERSION: 3
        OS_REGION_NAME: "IU"
        OS_INTERFACE: public
