name: Start

on:
  workflow_call:
    inputs:
      number:
        description: 'Number of runners to start.'
        required: false
        default: -1
        type: number

    secrets:
      OS_APPLICATION_CREDENTIAL_ID:
        required: false
      OS_APPLICATION_CREDENTIAL_SECRET:
        required: false

    outputs:
      active:
        description: "The number of active runners."
        value: ${{ jobs.action_runners.outputs.active }}

jobs:
  action_runners:
    name: action runners
    runs-on: ubuntu-latest
    outputs:
      active: ${{ steps.start.outputs.active }}
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: glotzerlab/jetstream2-admin
        ref: v1.3.0
    # Python 3.9 is the latest possible because netifaces has no new releases
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.9"
    - name: Install openstack
      uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049 # 0.2.0
      with:
        lockfile: ".github/workflows/requirements.txt"
    - id: start
      name: Start action runners
      run: |
        echo "active=$(python3 start/start-action-runners.py ${{ inputs.number }})" >> $GITHUB_OUTPUT
      env:
        OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        OS_AUTH_TYPE: v3applicationcredential
        OS_AUTH_URL: https://js2.jetstream-cloud.org:5000/v3/
        OS_IDENTITY_API_VERSION: 3
        OS_REGION_NAME: "IU"
        OS_INTERFACE: public
