name: Test

on:
  pull_request:

  workflow_dispatch:

jobs:
  start_workflow:
    name: Start
    uses: ./.github/workflows/start.yaml
    with:
      number: 1
    secrets: inherit

  check_output:
    name: Check output
    needs: start_workflow
    runs-on: ubuntu-latest

    steps:
    - name: "Check active runners"
      run: |
        echo Number of active runners: ${{ needs.start_workflow.outputs.active }}
        if [[ "${{ needs.start_workflow.outputs.active }}" != "1" ]]
        then
          echo "::error:: The action runner failed to start."
          exit 1
        fi
